const eventsData = [
  {
    id: 1,
    title: "number 1",
    agenda: "agenda 1",
    registrationUrl: "registrationUrl 1",
    banner: "banner 1",
    date: "date 1",
    startTime: "startTime 1",
    endTime: "endTime 1",
    price: "price 1",
    procurementPrice: "procurementPrice 1",
    discountPercent: "discountPercent 1",
    speaker: {
      firstName: "firstName 1",
      middleName: "middleName 1",
      lastName: "lastName 1",
      lastNameGenitive: "lastNameGenitive 1",
      regalia: "regalia 1",
      photo: "photo 1",
    },
    upcomingEvents: [],
    email: {
      subject: "subject 1",
      sendDatetime: "sendDatetime 1",
    },
  },
  {
    id: 2,
    title: "number 2",
    agenda: "agenda 2",
    registrationUrl: "registrationUrl 2",
    banner: "banner 2",
    date: "date 2",
    startTime: "startTime 2",
    endTime: "endTime 2",
    price: "price 2",
    procurementPrice: "procurementPrice 2",
    discountPercent: "discountPercent 2",
    speaker: {
      firstName: "firstName 2",
      middleName: "middleName 2",
      lastName: "lastName 2",
      lastNameGenitive: "lastNameGenitive 2",
      regalia: "regalia 2",
      photo: "photo 2",
    },
    upcomingEvents: [],
    email: {
      subject: "subject 2",
      sendDatetime: "sendDatetime 2",
    },
  },
  {
    id: 3,
    title: "number 3",
    agenda: "agenda 3",
    registrationUrl: "registrationUrl 3",
    banner: "banner 3",
    date: "date 3",
    startTime: "startTime 3",
    endTime: "endTime 3",
    price: "price 3",
    procurementPrice: "procurementPrice 3",
    discountPercent: "discountPercent 3",
    speaker: {
      firstName: "firstName 3",
      middleName: "middleName 3",
      lastName: "lastName 3",
      lastNameGenitive: "lastNameGenitive 3",
      regalia: "regalia 3",
      photo: "photo 3",
    },
    upcomingEvents: [],
    email: {
      subject: "subject 3",
      sendDatetime: "sendDatetime 3",
    },
  },
]